version: "3"
services:
  selenium:
    image: selenium/hub
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444      
      
  chrome:
     image: selenium/node-chrome:4.10.0-20230607
     shm_size: 2gb
     depends_on:
       - selenium
     environment:
          - SE_EVENT_BUS_HOST=selenium
          - SE_EVENT_BUS_PUBLISH_PORT=4442
          - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
          - SE_VNC_NO_PASSWORD=1
       

          
  firefox:
     image: selenium/node-firefox:4.10.0-20230607
     shm_size: 2gb
     depends_on:
       - selenium
     environment:
          - SE_EVENT_BUS_HOST=selenium
          - SE_EVENT_BUS_PUBLISH_PORT=4442
          - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
          - SE_VNC_NO_PASSWORD=1
     
          
  edge:
     image: selenium/node-edge:4.10.0-20230607
     shm_size: 2gb
     depends_on:
       - selenium
     environment:
          - SE_EVENT_BUS_HOST=selenium
          - SE_EVENT_BUS_PUBLISH_PORT=4442
          - SE_EVENT_BUS_SUBSCRIBE_PORT=4443    
          - SE_VNC_NO_PASSWORD=1 
       
